const fs=require('fs'),assert=require('assert');
const html=fs.readFileSync('index.html','utf8'),css=fs.readFileSync('r14_native_forms.css','utf8'),app=fs.readFileSync('app.js','utf8'),sw=fs.readFileSync('sw.js','utf8');
assert(html.includes('r14_native_forms.css'));
assert(!html.includes('class="deploy-wrap"'));
assert(html.includes('id="deploy-native"'));
assert(html.includes('id="facility-summary"'));
assert(css.includes('#battle-pause{left:541px!important;top:0!important;width:37px!important;height:37px!important'));
assert(css.includes('#battle-back{left:0!important;top:293px!important;width:37px!important;height:37px!important'));
assert(css.includes('#round-btn{left:541px!important;top:293px!important;width:37px!important;height:37px!important'));
assert(css.includes('#battle-actions{left:140px!important;bottom:0!important;transform:none!important;width:270px!important;height:11px!important'));
assert(css.includes('#battle-list{left:410px!important;right:auto!important;top:23px!important;width:160px!important;height:275px!important'));
assert(css.includes('.intro{left:42px!important;top:232px!important;width:345px!important;height:88px!important'));
assert(css.includes('#battle-confirm{left:468px!important;top:298px!important;width:80px!important;height:22px!important'));
assert(css.includes('#deploy-generals{position:absolute;left:30px;top:85px;width:508px;height:204px;display:grid;grid-template-columns:repeat(6,78px)'));
assert(css.includes('#facility-card.native-recruit{left:63px!important;top:68px!important;width:441px!important;height:185px!important'));
assert(css.includes('#general-detail{left:64px!important;top:51px!important;width:440px!important;height:217px!important'));
assert(css.includes('#equipment-picker{left:108px!important;top:30px!important;width:353px!important;height:261px!important'));
assert(css.includes('#commerce-panel[data-mode="market"]{left:64px!important;top:30px!important;width:440px!important;height:259px!important'));
assert(css.includes('#commerce-panel[data-mode="shop"]{left:72px!important;top:30px!important;width:425px!important;height:259px!important'));
assert(css.includes('#commerce-panel[data-mode="tavern"]{left:134px!important;top:23px!important;width:300px!important;height:275px!important'));
assert(!app.includes('function materializeDeployAssignments()'));
assert(!app.includes('prepareDeployment('));
assert(app.includes("addBattleAction('button_generals','部署将领',()=>openGeneralDeploymentForUnit(u)"));
assert(app.includes('function openGeneralDeploymentForUnit(u)'));
assert(app.includes('function commitGeneralDeployment()'));
assert(app.includes('EW4GeneralDeployment.assign(battleState.units,target.index,cid,battleState.playerOwner'));
assert(app.includes("document.getElementById('country-confirm').onclick=()=>{if(countryChoice==null){flash('先选择一个国家');return}"));
assert(app.includes("if(pending?.mode==='campaign')"));
assert(app.includes('EW4NativeCampaign.resolveVariant'));
assert(app.includes("openBattle(pending.battle,pending.map,{mode:'conquest'"));
assert(html.includes('id="deploy-confirm">部 署</button>'));
assert(!html.includes('id="deploy-confirm">出 征</button>'));
assert((html.match(/general_deployment_core\.js/g)||[]).length===1);
assert(app.includes("btn.style.setProperty('left',ai?'0px':'541px','important')"));
assert(app.includes("el.className='native-user-window native-recruit show'"));
assert(app.includes('shop-buyer-grid'));
assert(app.includes('tavern-recruit-label'));
assert(sw.includes('r14_native_forms.css'));

// r14-38 original form_getgeneral / Military Academy contract.
assert(html.includes('id="academy-back"'));
assert(!html.includes('id="academy" class="screen"><img class="fullbg" src="assets/textures/campaign_wide.png"><div class="titlebar">军事学院</div><button class="back" data-go="hq"'));
assert(html.includes('.academy-tabs{position:absolute;left:51px;top:36px;width:463px;height:55px'));
assert(html.includes('#academy-list{position:absolute;left:25px;top:110px;width:519px;height:98px'));
assert(html.includes('.academy-refresh{position:absolute;left:234px;top:257px;width:100px;height:40px'));
assert(html.includes('.academy-deco.d1{left:110px;transform:scale(-.8,.8)}'));
assert(html.includes('.academy-deco.d2{left:206px;transform:scale(.8)}'));
assert(html.includes('.academy-deco.d3{left:362px;transform:scale(-.8,.8)}'));
assert(html.includes('.academy-deco.d4{left:458px;transform:scale(.8)}'));
assert(html.includes('.academy-bottom-left{left:220px;transform:scale(-.5,.5)}'));
assert(html.includes('.academy-bottom-right{left:347px;transform:scale(.5)}'));
assert(html.includes('native_academy_core.js'));
assert(app.includes('function academyCandidateCount(){return EW4NativeAcademy.config(academyPool).count}'));
assert(app.includes('EW4NativeAcademy.ensurePools({commanders:COMMANDERS,owned:saveState.owned,pools:before})'));
assert(app.includes('EW4NativeAcademy.refreshTier({commanders:COMMANDERS,owned:saveState.owned,pools:saveState.academyCandidatesByPool,tier:academyPool})'));
assert(app.includes("academyPool=b.dataset.pool;saveState.academyPool=academyPool;academySelectedId=null;syncAcademyCandidates();persist();renderAcademy()"));
assert(!app.includes('poolList()'));
assert(sw.includes('native_academy_core.js'));
assert(app.includes("document.getElementById('deploy-college').onclick=()=>{hidePrincessDeploymentPanel();academyReturnScreen='deploy';go('academy')}"));
assert(app.includes("const academyBack=document.getElementById('academy-back')"));
assert(app.includes("const MODS=Object.freeze({medals:Infinity,badges:Infinity,academyRefresh:Infinity,generalCap:Infinity"));

console.log('original 568h forms contract PASS');
