'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const d=require('./assets/data/native_simple_effects.json');
assert.strictEqual(d.atlas,'assets/effects/eff.png');
assert(fs.existsSync(path.join(__dirname,d.atlas)));
const b=d.effects.effect_build,r=d.effects.effect_recover,m1=d.effects.effect_moving1,m2=d.effects.effect_moving2,m3=d.effects.effect_moving3,m4=d.effects.effect_moving4;
assert(b&&r&&m1&&m2&&m3&&m4);
assert.strictEqual(b.image,'build_mark.png');assert.strictEqual(b.particle_life_min,1.4);assert.strictEqual(b.scale_min,1.5);
assert.deepStrictEqual(b.atlas_rect,{x:245,y:97,w:81,h:70,refx:46,refy:33});
assert.strictEqual(r.image,'recover.png');assert.strictEqual(r.particle_life_min,1.3);assert.strictEqual(r.scale_min,1.0);
assert.deepStrictEqual(r.atlas_rect,{x:1,y:130,w:98,h:98,refx:48,refy:93});
assert.deepStrictEqual(b.timetrack,[{time:0,quantity:30},{time:0.1,quantity:0}]);
assert.deepStrictEqual(r.timetrack,[{time:0,quantity:30},{time:0.1,quantity:0}]);
assert.strictEqual(b.lifetrack.length,8);assert.strictEqual(r.lifetrack.length,11);
assert.deepStrictEqual(m1.atlas_rect,{x:377,y:162,w:64,h:64,refx:31,refy:29});
assert.deepStrictEqual(m1.settings,{name:'settings',mode:'cont',type:'area',width:'20',height:'20'});
assert.strictEqual(m1.image,'cloud5.png');assert.strictEqual(m1.speed_min,20);assert.strictEqual(m1.speed_max,25);assert.strictEqual(m1.gravity_min,-40);assert.strictEqual(m1.gravity_max,-20);
assert.strictEqual(m2.particle_width,40);assert.strictEqual(m3.particle_width,45);
assert.strictEqual(m4.image,'water001.png');assert.strictEqual(m4.blend,'add');assert.strictEqual(m4.settings.width,'10');assert.strictEqual(m4.settings.height,'10');
const sw=fs.readFileSync(path.join(__dirname,'sw.js'),'utf8');
assert(sw.includes('./assets/data/native_simple_effects.json'));
assert(sw.includes('./assets/effects/eff.png'));
console.log('native simple effects data PASS: build/recover + moving1-4 XML and original eff.png atlas preserved');
