'use strict';
const fs=require('fs'),assert=require('assert');
const E=require('./native_event_core.js');
const d=JSON.parse(fs.readFileSync('./assets/data/battle_native_triggers.json','utf8'));
const ev=[];
for(const [battle,b] of Object.entries(d.battles||{}))for(const e of b.events||[])if(+e.trigger_type===2&&[0,1,2].includes(+e.param_a))ev.push({...e,battle});
assert.equal(ev.length,31,'native round morale event count');
assert.equal(ev.filter(e=>+e.param_a===0).length,26);
assert.equal(ev.filter(e=>+e.param_a===1).length,3);
assert.equal(ev.filter(e=>+e.param_a===2).length,2);
assert(ev.every(e=>e.country),'all morale events need a country');
assert.equal(E.moraleForAction(0),1);assert.equal(E.moraleForAction(1),-1);assert.equal(E.moraleForAction(2),-2);
assert.equal(E.combinedMorale(-2,-2,false),-3,'native clamp floor');
assert.equal(E.combinedMorale(-1,-1,true),0,'leadership cancels low morale');
let us=[{owner:0},{owner:0},{owner:1}];
assert.equal(E.applyCountryMorale(us,'fra',1,5,o=>o===0?'fra':'gbr'),2);
assert.equal(us[0].nativeMoraleBase,-1);assert.equal(us[0].nativeMoraleUntilRound,8);
assert.equal(E.eventMoraleBase(us[0],7),-1);assert.equal(E.eventMoraleBase(us[0],8),0);
console.log('native morale events PASS',ev.length);
