'use strict';
const fs=require('fs'),assert=require('assert');
const html=fs.readFileSync('index.html','utf8'),app=fs.readFileSync('app.js','utf8'),sw=fs.readFileSync('sw.js','utf8'),layout=fs.readFileSync('assets/data/original_layout-568h.xml','utf8');
assert(layout.includes('<Layout id="form_loading" type="window">'));
assert(layout.includes('id="image_title" type="image" name="title.png" x="10" y="8"'));
assert(layout.includes('id="text_desc" type="text" font="font_text_2" x="20" y="150" w="527" h="80"'));
assert(layout.includes('id="text_loading" type="text" font="font_char_3" x="480" y="300"'));
assert(html.includes('id="loading" class="screen active native-loading-screen"'));
assert(!html.includes('id="main" class="screen active"'));
assert(html.includes('id="loading-title" src="assets/textures/loading_title_zh_cn.png"'));
assert(html.includes('#loading-title{position:absolute;left:10px;top:8px;width:379px;height:96px'));
assert(html.includes('#loading-desc{position:absolute;left:20px;top:150px;width:527px;height:80px'));
assert(html.includes('#loading-text{position:absolute;left:480px;top:300px'));
assert(app.includes('const tip=1+Math.floor(Math.random()*24)'));
assert(app.includes("strings?.[`text_tips_${tip}`]"));
assert(app.includes("strings?.text2_loading||'载入……'"));
assert(app.includes("if(!STRINGS)STRINGS=await fetchJSON('assets/data/strings_cn.json')"));
assert(app.includes("await loadDB();"));
assert(app.includes("go('main');"));
assert(app.trimEnd().endsWith('bootNativeApp();'));
assert(sw.includes("'./assets/textures/loading_title_zh_cn.png'"));
assert(fs.existsSync('assets/textures/loading_title_zh_cn.png'));
console.log('P30 native form_loading startup contract PASS');
