'use strict';
const fs=require('fs'),assert=require('assert');
const data=JSON.parse(fs.readFileSync('assets/data/native_effects_audio.json','utf8'));
const core=require('./native_effect_audio_core.js');
const app=fs.readFileSync('app.js','utf8');
let c=core.scheduledAudioCues(data,'militia 1 right',1);
assert.deepStrictEqual(c.map(x=>x.delayMs),[920,1040,1170]);
c=core.scheduledAudioCues(data,'machine gun 1 right',1);
assert.deepStrictEqual(c.map(x=>x.delayMs),[500,500]);
assert(c.every(x=>x.sound==='sfx_machine_gun.wav'));
c=core.scheduledAudioCues(data,'rocket 1 right',1);
assert.deepStrictEqual(c.map(x=>x.delayMs),[1600,1800,2000]);
const ff=core.scheduledAudioCues(data,'rocket 1 right',20);
assert.deepStrictEqual(ff.map(x=>x.delayMs),[80,90,100]);
assert(app.includes("fetchJSON('assets/data/native_effects_audio.json')"));
assert(app.includes('scheduleNativeAttackSfx(u,target,speed)'));
assert(app.includes('playNativeSfxFile(cue.sound)'));
assert(!app.includes("playSfx(st.weapon==='cannon'"),'old guessed immediate attack SFX must be removed');
console.log('native timed battle SFX PASS: def_effectsanim at= seconds drive battle sounds; AI presentation scaling isolated');
