'use strict';
const assert=require('assert'),fs=require('fs');
const C=require('./native_campaign_core.js');
const data=JSON.parse(fs.readFileSync('./assets/data/battles_runtime.json','utf8'));const battles=Array.isArray(data)?data:data.battles;
const layout=fs.readFileSync('./assets/data/original_layout-568h.xml','utf8'),html=fs.readFileSync('./index.html','utf8'),css=fs.readFileSync('./r14_native_forms.css','utf8'),app=fs.readFileSync('./app.js','utf8'),sw=fs.readFileSync('./sw.js','utf8');
const form=(layout.match(/<Layout id="form_selcountry"[\s\S]*?<\/Layout>/)||[])[0]||'';
assert(/w="234" h="150"/.test(form));assert(/id="btn_left"[^>]*x="17" y="36" w="85" h="67"/.test(form));assert(/id="btn_right"[^>]*x="132" y="36" w="85" h="67"/.test(form));assert(/id="group_select"[^>]*x="17" y="36" w="85" h="67"/.test(form));assert(/id="scale_bottom_line"[^>]*x="0" y="119" h="2"/.test(form));assert(/id="image_bottom_flower"[^>]*y="125"/.test(form));
assert(html.includes('id="campaign-country-overlay"'));assert(html.includes('id="campaign-country-left"'));assert(html.includes('id="campaign-country-right"'));assert(html.includes('id="campaign-country-selected"'));assert(html.includes('id="campaign-country-confirm"'));
assert(css.includes('#campaign-country-panel{left:167px;top:85px;width:234px;height:150px'));assert(css.includes('#campaign-country-left{left:17px}#campaign-country-right{left:132px}'));assert(css.includes('#campaign-country-selected{position:absolute;left:17px;top:36px;width:85px;height:67px'));assert(css.includes('.campaign-country-bottom-line{position:absolute;left:0;top:119px;width:234px;height:2px'));assert(css.includes('.campaign-country-bottom-flower{position:absolute;left:101px;top:125px'));
assert(app.includes("selectCampaignCountry(pair[0])"),'native default must be left country');assert(app.includes("playNativeFormOpenSfx('form_selcountry')"));assert(!/openCampaignCountrySelect[\s\S]{0,1800}go\('countrySelect'\)/.test(app),'campaign branch selector must not reuse conquest full-screen selector');
for(const [file,right] of [['campaign3_08.btl','campaign3_08b.btl'],['campaign4_10.btl','campaign4_10b.btl']]){const b=battles.find(x=>x.file===file),codes=C.selectableCountryCodes(b);assert.strictEqual(codes.length,2);const l=C.resolveVariant(b,codes[0],battles),r=C.resolveVariant(b,codes[1],battles);assert.strictEqual(l.battle.file,file);assert.strictEqual(l.variant,false);assert.strictEqual(r.battle.file,right);assert.strictEqual(r.variant,true);assert.strictEqual(l.playerCode,codes[0]);assert.strictEqual(r.playerCode,codes[1]);}
for(const f of ['common_lineframe_bold.png','button_lottery_generals.png','common_boldline.png','pru1.png','aus1.png','tur1.png','rus1.png'])assert(sw.includes(f),`offline CORE missing ${f}`);
console.log('P26 native Campaign form_selcountry: PASS');
