const fs=require('fs');
const assert=(x,m)=>{if(!x)throw new Error(m)};
const app=fs.readFileSync('app.js','utf8');
const html=fs.readFileSync('index.html','utf8');
const css=fs.readFileSync('r14_native_forms.css','utf8');
assert(html.includes('id="main-hq"'),'main HQ dedicated native-controller entry missing');
assert(!html.includes('id="hq"'),'legacy Web HQ screen must not exist');
assert(!html.includes('id="hq-grid"'),'legacy Web HQ grid must not exist');
assert(!app.includes('function renderHQ('),'legacy renderHQ controller must be removed');
assert(!app.includes("hqFilter='all'"),'legacy HQ filter state must be removed');
assert(app.includes('function openHeadquartersDeployment()'),'native HQ -> deploygeneral entry missing');
assert(app.includes("deploymentContext='hq'"),'HQ deploygeneral context missing');
assert(app.includes("mainHqBtn.onclick=openHeadquartersDeployment"),'main HQ must enter deploygeneral controller');
assert(app.includes("go('deploy')"),'HQ must render the shared deploygeneral scene');
assert(app.includes("hqMode=deploymentContext==='hq'"),'deploygeneral HQ context branch missing');
assert(app.includes('if(hqMode){openHQCommander(c);return}'),'HQ general grid must open general info instead of battle assignment');
assert(app.includes("if(deploymentContext!=='battle')return false"),'battle deployment must be gated from HQ context');
assert(css.includes('#deploy-princess{left:20px;top:30px}'),'native deploygeneral princess geometry missing');
assert(css.includes('#deploy-shop{left:249px;top:30px'),'native deploygeneral shop geometry missing');
assert(css.includes('#deploy-college{left:480px;top:30px}'),'native deploygeneral college geometry missing');
assert(css.includes('#deploy-generals{position:absolute;left:30px;top:85px;width:508px;height:204px'),'native deploygeneral grid geometry missing');
console.log('native headquarters/deploygeneral flow PASS');
