const fs=require('fs'),assert=require('assert');
const L=require('./native_lowzoom_core.js');
const app=fs.readFileSync('app.js','utf8');
const html=fs.readFileSync('index.html','utf8');
const manifest=JSON.parse(fs.readFileSync('assets/sprite_manifest.json','utf8'));
for(const k of ['hpbar_blue.png','hpbar_red.png','hpbar_green.png','hpbar_black.png','hpbar_hp.png'])assert(manifest[k],`${k} missing`);
assert.strictEqual(L.relationSprite('player'),'hpbar_green.png');
assert.strictEqual(L.relationSprite('ally'),'hpbar_blue.png');
assert.strictEqual(L.relationSprite('hostile'),'hpbar_red.png');
assert.strictEqual(L.relationSprite('neutral'),'hpbar_black.png');
assert.deepStrictEqual(L.hpColorRGB(0),{r:255,g:0,b:0});
assert.deepStrictEqual(L.hpColorRGB(.5),{r:255,g:255,b:0});
assert.deepStrictEqual(L.hpColorRGB(1),{r:0,g:255,b:128});
assert(Math.abs(L.HP_START_RAD-(171*Math.PI/180))<1e-6,'native HP start angle drifted');
assert(Math.abs(L.HP_FULL_SWEEP_RAD-(198*Math.PI/180))<1e-6,'native HP full sweep drifted');
assert(Math.abs(L.hpArc(.25).sweep-(49.5*Math.PI/180))<1e-6,'HP ratio must scale native sweep');
assert(html.includes('<script src="native_lowzoom_core.js"></script>'),'lowzoom core not loaded');
assert(app.includes('relation ring -> dynamic HP arc -> mark_unit army icon'),'native strategic composition missing');
assert(app.includes('EW4NativeLowZoom.relationSprite(rel)'),'relation ring renderer not wired');
assert(app.includes('EW4NativeLowZoom.hpArc(hpRatio)'),'native HP arc renderer not wired');
assert(app.indexOf('EW4NativeLowZoom.hpArc(hpRatio)')<app.indexOf('SPRITES?.[`mark_unit_${id}.png`]'),'HP arc must render before mark_unit icon');
console.log('native low-zoom relation/HP status layer: PASS');
