const assert=require('assert');const fs=require('fs');const path=require('path');
const root=__dirname,core=require('./native_campaign_line_core.js');
const xml=fs.readFileSync(path.join(root,'assets/data/def_battleline.xml'),'utf8'),rows=core.parse(xml);
assert.strictEqual(rows.length,6,'all six original battle lines must parse');
assert.deepStrictEqual(rows[0],{name:'imperialeagle',hide:0,start:1793,end:1820,stars:10,countries:['fra']});
assert.deepStrictEqual(rows[1].countries,['aus','pru','rus','gbr']);
assert.deepStrictEqual(rows[5],{name:'neversets',hide:1,start:1775,end:1814,stars:10,countries:['gbr']});
assert.strictEqual(core.titleKey(rows[2]),'name_romanempire');
const layout=fs.readFileSync(path.join(root,'assets/data/original_layout-568h.xml'),'utf8');
const form=(layout.match(/<Layout id="form_campaigninfo"[\s\S]*?<\/Layout>/)||[])[0]||'';
for(const q of ['w="155" h="83"','name="button_choosebattlezoneinfo.png" x="-9" y="-4" h="70"','name="arrow_choosebattlezoneinfo.png" x="60" y="56"','id="lbox_nation" type="listbox" x="4" y="34" w="150" h="15"','frm1="button_confrim.png" x="110" y="28" w="31" h="32"'])assert(form.includes(q),`original form evidence missing: ${q}`);
const html=fs.readFileSync(path.join(root,'index.html'),'utf8'),css=fs.readFileSync(path.join(root,'r14_native_forms.css'),'utf8'),app=fs.readFileSync(path.join(root,'app.js'),'utf8'),sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');
for(const id of ['campaigninfo-native','campaigninfo-back','campaigninfo-arrow','campaigninfo-title','campaigninfo-age','campaigninfo-tips','campaigninfo-nations','campaigninfo-confirm'])assert(html.includes(`id="${id}"`),`missing ${id}`);
assert(html.includes('<script src="native_campaign_line_core.js"></script>'));
for(const q of ['#campaigninfo-native{position:absolute;width:155px;height:83px','#campaigninfo-arrow{position:absolute;left:60px;top:56px;width:31px;height:22px','#campaigninfo-confirm{position:absolute;left:110px;top:28px;width:31px;height:32px'])assert(css.includes(q),`campaigninfo CSS mismatch: ${q}`);
assert(app.includes("fetchText('assets/data/def_battleline.xml')"),'runtime must load original def_battleline.xml');
assert(app.includes('NATIVE_BATTLELINES=EW4NativeCampaignLine.parse(NATIVE_BATTLELINE_XML)'));
assert(app.includes("openNativeCampaignInfo(+b.dataset.zone,b)"),'campaign pin must enter native info controller');
assert(!app.includes("document.querySelectorAll('.campaign-pin').forEach(b=>b.onclick=()=>openZone(+b.dataset.zone))"),'direct zone skip controller must be removed');
assert(app.includes("document.getElementById('campaigninfo-confirm')?.addEventListener"));
for(const q of ['./native_campaign_line_core.js','./assets/data/def_battleline.xml','./assets/sprites/image_ui_hd/button_choosebattlezoneinfo.png','./assets/sprites/image_ui_hd/arrow_choosebattlezoneinfo.png','./assets/sprites/image_ui_hd/button_confrim.png'])assert(sw.includes(`'${q}'`),`SW missing ${q}`);
console.log('P25 native campaigninfo: PASS (6/6 original battle lines + 155x83 controller + pin->info->confirm flow)');
