const fs=require('fs'),assert=require('assert');
const anim=require('./native_animation_controller.js');
const core=JSON.parse(fs.readFileSync('assets/data/native_animation_core265.json','utf8'));
const html=fs.readFileSync('index.html','utf8'),app=fs.readFileSync('app.js','utf8'),sw=fs.readFileSync('sw.js','utf8');
assert(html.indexOf('compact_bile_runtime.js')>=0);
assert(html.indexOf('compact_bile_runtime.js')<html.indexOf('native_animation_controller.js'));
assert(app.includes("new EW4CompactBile.BrowserPack('assets/bile_runtime')"));
assert(app.includes('preloadCompactBileResource(a.resource)'));
assert(app.includes("nativeSpec?.kind==='compact'"));
assert(app.includes('nativeSpec.bile.drawFrame(ctx'));
assert(!/nativeFrameDrawSpec[\s\S]{0,1400}runtime_sheet\.file/.test(app),'production nativeFrameDrawSpec must not depend on expanded runtime_sheet.png');
const militia=core.units['Militia 1'];
assert(militia);
assert.deepStrictEqual(anim.compactDrawOrigin(militia,{x:450,y:350},1),{x:433,y:326.5,scale:.5});
assert.deepStrictEqual(anim.compactDrawOrigin(militia,{x:450,y:350},2),{x:416,y:303,scale:1});
const stems=['army_armoredcar','army_artillery','army_fort','army_grenadier','army_guards','army_guardscavalry','army_heavycavalry','army_lightcavalry','army_lightinfantry','army_lineinfantry','army_militia','army_ship'];
for(const f of ['manifest.json','def_motion.xml',...stems.flatMap(s=>[s+'.bin',s+'.xml',s+'.png'])])assert(sw.includes(`./assets/bile_runtime/${f}`),`SW compact cache ${f}`);
assert(sw.includes("'./compact_bile_runtime.js'"));
console.log('compact BILE production-render contract PASS · direct Canvas path + native anchor math + offline source cache');
