'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const core=require('./native_action_audio_core.js');
const ROOT=__dirname;
assert.strictEqual(core.actionSfx('recruit'),'sfx_draft.wav');
assert.strictEqual(core.actionSfx('occupy'),'sfx_occupy.wav');
assert.strictEqual(core.actionSfx('buildInstallation'),'sfx_build.wav');
assert.strictEqual(core.actionSfx('upgradeConstruction'),'sfx_build1.wav');
assert.strictEqual(core.actionSfx('training'),'sfx_buff.wav');
assert.strictEqual(core.actionSfx('supply'),'sfx_supply.wav');
assert.strictEqual(core.movementSfx({army_name:'Line Infantry'},{type:'infantry'}),'sfx_leg.wav');
assert.strictEqual(core.movementSfx({army_name:'Light Artillery'},{type:'artillery'}),'sfx_leg.wav');
assert.strictEqual(core.movementSfx({army_name:'Light Cavalry'},{type:'cavalry'}),'sfx_cavalrymove.wav');
assert.strictEqual(core.movementSfx({army_name:'Armored Car'},{type:'cavalry'}),'sfx_armourmove.wav');
assert.strictEqual(core.movementSfx({army_name:'Frigate'},{type:'warship'}),'sfx_naval.wav');
assert.strictEqual(core.movementSfx({army_name:'Line Infantry',embarked:true},{type:'infantry'}),'sfx_naval.wav');
for(const f of ['sfx_draft.wav','sfx_occupy.wav','sfx_build.wav','sfx_build1.wav','sfx_buff.wav','sfx_supply.wav','sfx_leg.wav','sfx_cavalrymove.wav','sfx_armourmove.wav','sfx_naval.wav'])assert(fs.existsSync(path.join(ROOT,'assets/audio',f)),f);
const app=fs.readFileSync(path.join(ROOT,'app.js'),'utf8');
const sw=fs.readFileSync(path.join(ROOT,'sw.js'),'utf8');
assert(sw.includes('./native_action_audio_core.js'));
assert(app.includes("playNativeActionSfx('occupy')"));
assert(app.includes("playNativeActionSfx('recruit')"));
assert(app.includes("playNativeActionSfx('buildInstallation')"));
assert(app.includes("playNativeActionSfx('upgradeConstruction')"));
assert(app.includes('playNativeMovementSfx(u)'));
assert(!app.includes("captureAt(u);playSfx(armyStat(u).type==='cavalry'?'cavalry':'select')"));
console.log('native action audio: PASS');
