'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path');
const root=__dirname,app=fs.readFileSync(path.join(root,'app.js'),'utf8'),html=fs.readFileSync(path.join(root,'index.html'),'utf8'),sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');
const G=require('./native_general_core.js'),items=require('./assets/data/items.json');
assert.ok(app.includes('function awardNativeGeneralCombatGrowth('),'battle general growth bridge missing');
assert.ok(app.includes('EW4NativeGeneral.battleMilitaryGain(damage,ctx)'),'military growth not wired');
assert.ok(app.includes('EW4NativeGeneral.battleNobilityGain(victim?.grade,victim?.commander_id!=null,ctx)'),'nobility kill growth not wired');
assert.ok(/awardNativeGeneralCombatGrowth\(a,b,out\.value,killed\)/.test(app),'applyDamage must award native commander growth');
assert.ok(app.includes("if(!c||!owns(c.id))return null"),'scenario/enemy generals must not mutate HQ growth');
assert.ok(app.includes('setGeneralGrowth(c,{rank:m.level,militaryProgress:m.progress,nobility:n.level,nobleProgress:n.progress})'),'growth persist bridge missing');
assert.ok(app.includes("openGeneralUpgrade(c)"));assert.ok(app.includes("hq-upgrade-hotspot"),'HQ info/upgrade actions not separated');
assert.ok(app.includes("saveState.owned=saveState.owned.filter(id=>+id!==+source.id)"),'regroup source delete missing');
assert.ok(app.includes("saveState.equipment[sid]=[null,null]"),'regroup source item disappearance override missing');
assert.ok(!app.includes('openEquipmentPicker('),'old direct Web equipment picker must be removed');
assert.ok(app.includes('function openDeployItem('));assert.ok(app.includes('function commitDeployItem('));assert.ok(app.includes('bank.slots.forEach((entry,i)=>'),'DeployItem must render all ItemBank slots');
for(const id of ['equipment-picker','eq-prev','eq-next','eq-portrait','eq-rank','eq-nobility','eq-equipped','eq-desc','eq-grid','eq-equip'])assert.ok(html.includes(`id="${id}"`),`missing DeployItem control ${id}`);
assert.ok(sw.includes("native_general_core.js"));assert.ok(/posthandoff(?:18-general|19-residual|[2-9][0-9])/.test(sw),'P18 or later cache generation required');
const table=items.items||items;
assert.strictEqual(G.growthMultiplier('nobility',{items:[table['2']],skills:[19]}),4);
assert.strictEqual(G.growthMultiplier('military',{items:[table['4']],skills:[21]}),3);
console.log('P18 native general integration: PASS');
